name: arch

description: A scalable, testable, maintainable Flutter Todo app with local database.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  get_it: ^8.2.0
  uuid: ^4.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
